name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
      run: dotnet build --configuration Release --framework netcoreapp3.0
    - name: Test with dotnet
      run: dotnet test --configuration Release --framework netcoreapp3.0
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: 'TChapter.dll'
        path: /home/runner/work/TChapter/TChapter/TChapter/bin/Release/netcoreapp3.0/TChapter.dll
