name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build with dotnet
      run: dotnet build --configuration Release --framework net4.5
    - name: Test with dotnet
      run: dotnet test --configuration Release --framework net4.5
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: 'TChapter.dll'
        path: /home/runner/work/TChapter/TChapter/TChapter/bin/Release/net/TChapter.dll
